define({
    preFix:'http://web.yylm.com/public/index.php/unionShop',
    shop:{
        shopInfo:'/index/index',
        goodslist:'/index/getGoodsList', 
        bankCardList:'/order/bankCarList',
        addBankCard:'/order/addBankCar',
    },
    shopOrder:{
        orderlist:'/order/indexList',
        verifyOrderCode:'/order/sellGoodsCheck',
        //订单校验成功后改变状态
        orderStatus:'/order/goodsChangeStatus',
        //商户账户资金展示
        orderAccount:'/order/getAccount',
        //提现记录展示
        showOutPay:'/order/withdList',
        //申请提现 
        applyMoney:'/order/getMoney'
    }

});