define({
    preFix:'/shop/shop/public/index.php/admin',
    obligation:{
        showlist:'/debtnexus/index',
        update:'/debtnexus/edit',
        typeshow:'/Proportion/show',
        typeAdd:'/Proportion/add',
        updateType:'/Proportion/edit'
    },
    article:{
        showlist:'/Article/lst',
        addSingle:'/Article/add',
        updateSingle:'/Article/update',
        changeStatus:'/Article/beginStopUse'
    }
});