define({
    preFix:'/shop/shop/public/index.php/admin',
    obligationPreFix:'http://web.yylm.com/public/bfapp',
    obligation:{
        showlist:'/debtnexus/index',
        update:'/debtnexus/edit',
        typeshow:'/Proportion/show',
        typeAdd:'/Proportion/add',
        updateType:'/Proportion/edit',
        updateListByTypeId:'/proportion/showgood',
        searchFilterGoods:'/proportion/searchgood',
        addObligationGoods:'/proportion/editStandard',
        deleteObligationGoods:'/proportion/delgoodtandard',
        classifyList:'/Goodsclass/classList',
        addClass:'/Goodsclass/addClass',
        updateClass:'/Goodsclass/upClass',
        getOneClass:'/Goodsclass/oneClass',
        updateStatusType:'/Goodsclass/onOff',
        goods:{
            showlist:'/goods/goodsList',
            getOneInfo:'/goods/oneGoods',
            addGoods:'/goods/addGoods',
            updateGoods:'/goods/upGoods',
            copyGoods:'/goods/copyGoods',
            upordownGoods:'/goods/onOff',
            lookInfoCopyed:'/goods/beforeId',
            searchFilterGoods:'/relevance/goodsList'
            
        }
    },
    article:{
        showlist:'/Article/lst',
        addSingle:'/Article/add',
        updateSingle:'/Article/update',
        changeStatus:'/Article/beginStopUse'
    },
    distributeShare:{
        sharelist:'/share/show',
        updateShareInfo:'/share/editShare',
        disShareList:'/sharesub/show',
        updateDisShareInfo:'/sharesub/editSubShare'
    }
});